on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: thomaschln/knowledgegraphs:main

    steps:
      - uses: actions/checkout@v4          
      - uses: r-lib/actions/check-r-package@v2
